FROM golang:1.26.5-alpine

RUN apk add --no-cache git \
  && go install github.com/air-verse/air@v1.52.3

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY .air.toml ./

CMD ["air", "-c", ".air.toml"]
