package integration

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"slices"
	"strings"
	"testing"
	"time"
)

// THE CONSENT EVIDENCE PACK (#568, spec #556, ADR 0067): one file that answers a
// data subject or a regulator, generated on demand from the per-subject record
// and never stored.
//
// WHAT THIS SLICE MUST PROVE, beyond "the endpoint returns a ZIP":
//
//   - THE CONTENTS. `record.json`, `evidence.pdf`, and the texts as RAW `.md`
//     files under `texts/<document>/<edition-label>/<locale>/<ordinal>-<slug>.md`
//     — deduplicated by edition, and in EVERY LOCALE of every edition named,
//     because the fingerprint spans an edition's languages at once and a
//     single-locale pack could not verify its own hash.
//   - THE DETERMINISM. Two packs over identical acts are BYTE-IDENTICAL. It is
//     what allows migration 118 to store a hash instead of a file, and it is why
//     the pack carries `published_as` and no current-gating flag.
//   - IT SPANS BOTH POPULATIONS FOR ONE ADDRESS, and both routes serve the same
//     bytes: one access request has one answer.
//   - THE EMPTY CASE IS A FILE. "We hold nothing about this person" is provable
//     rather than an error.
//   - THE HMAC DIGEST APPEARS NOWHERE IN THE CONTENTS (#548) — including in the
//     pack generated by the route that was REACHED BY a digest, which is the
//     case where one would most plausibly leak.
//   - ONLY THE HASH AND THE COVERED ACT IDS ARE PERSISTED. No copy of the pack
//     is anywhere in the database.
//   - OPERATOR ONLY, and no subject-facing download exists.

func evidencePackPath(customerID string) string {
	return legalCustomerRecordPath(customerID) + "/evidence-pack"
}

func staffEvidencePackPath(digest string) string {
	return legalStaffRecordPath(digest) + "/evidence-pack"
}

// downloadPack fetches a pack and reads the archive back.
type downloadedPack struct {
	Filename string
	SHA256   string
	Header   http.Header
	Body     []byte
	Names    []string
	Files    map[string][]byte
}

func downloadPack(t *testing.T, env *testEnv, sessionID, path string) downloadedPack {
	t.Helper()
	resp, body := env.getRaw(t, path, authHeader(sessionID))
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("GET %s status=%d body=%s", path, resp.StatusCode, body)
	}
	if ct := resp.Header.Get("Content-Type"); ct != "application/zip" {
		t.Fatalf("Content-Type=%q; want application/zip", ct)
	}
	disposition := resp.Header.Get("Content-Disposition")
	filename := strings.TrimSuffix(strings.TrimPrefix(disposition, `attachment; filename="`), `"`)
	if filename == disposition || filename == "" {
		t.Fatalf("Content-Disposition=%q; want an attachment with a filename", disposition)
	}

	reader, err := zip.NewReader(bytes.NewReader(body), int64(len(body)))
	if err != nil {
		t.Fatalf("the pack is not a readable ZIP: %v", err)
	}
	pack := downloadedPack{
		Filename: filename,
		SHA256:   resp.Header.Get("X-Pack-SHA256"),
		Header:   resp.Header,
		Body:     body,
		Files:    map[string][]byte{},
	}
	for _, file := range reader.File {
		pack.Names = append(pack.Names, file.Name)
		opened, err := file.Open()
		if err != nil {
			t.Fatalf("open %s: %v", file.Name, err)
		}
		content, err := io.ReadAll(opened)
		opened.Close()
		if err != nil {
			t.Fatalf("read %s: %v", file.Name, err)
		}
		pack.Files[file.Name] = content
	}
	return pack
}

// packRecord parses record.json the way a regulator's script would: loosely,
// through the file rather than through the server's structs.
func packRecord(t *testing.T, pack downloadedPack) map[string]any {
	t.Helper()
	raw, ok := pack.Files["record.json"]
	if !ok {
		t.Fatalf("the pack holds no record.json: %v", pack.Names)
	}
	var parsed map[string]any
	if err := json.Unmarshal(raw, &parsed); err != nil {
		t.Fatalf("record.json is not valid JSON: %v", err)
	}
	return parsed
}

// TestTheEvidencePackHoldsTheRecordItsReadingAndTheRawTexts walks the contents
// against a real record, over the real published editions.
func TestTheEvidencePackHoldsTheRecordItsReadingAndTheRawTexts(t *testing.T) {
	env := setupTest(t)
	setConsentClock(fixedClock)
	signInAnswering(t, env, "ana@example.com", true, true, false)
	customerID := customerIDFor(t, env, "ana@example.com")
	sessionID := operatorSession(t, env, "operator@example.com")

	pack := downloadPack(t, env, sessionID, evidencePackPath(customerID))

	// FIXED ENTRY ORDERING: the record, its reading, then the texts by path.
	if pack.Names[0] != "record.json" || pack.Names[1] != "evidence.pdf" {
		t.Fatalf("the pack starts with %v; want record.json then evidence.pdf", pack.Names[:2])
	}
	texts := pack.Names[2:]
	if len(texts) == 0 {
		t.Fatal("the pack carries no texts; an act naming an edition must resolve to bytes")
	}
	if !slices.IsSorted(texts) {
		t.Fatalf("the text entries are not in path order: %v", texts)
	}
	if !bytes.HasPrefix(pack.Files["evidence.pdf"], []byte("%PDF")) {
		t.Fatal("evidence.pdf is not a PDF")
	}
	// RAW MARKDOWN, not JSON strings: verification is a shell script over bytes.
	for _, name := range texts {
		if !strings.HasPrefix(name, "texts/") || !strings.HasSuffix(name, ".md") {
			t.Fatalf("unexpected entry %q", name)
		}
		if len(pack.Files[name]) == 0 {
			t.Fatalf("%s is empty", name)
		}
	}

	// EVERY LOCALE OF EVERY EDITION NAMED. The signed-in Customer was shown one
	// language; the pack carries both, because the fingerprint covers both.
	locales := map[string]bool{}
	for _, name := range texts {
		parts := strings.Split(name, "/")
		locales[parts[3]] = true
	}
	if !locales["en"] || !locales["es"] {
		t.Fatalf("the pack carries only %v; the hash spans every language at once", locales)
	}

	// The record names the person and the acts, and the acts are the record
	// screen's own rows.
	record := packRecord(t, pack)
	subject, _ := record["subject"].(map[string]any)
	if subject["email"] != "ana@example.com" {
		t.Fatalf("subject = %v", subject)
	}
	acts, _ := record["customer_acts"].([]any)
	if len(acts) == 0 {
		t.Fatal("record.json carries no acts for somebody who has just answered three boxes")
	}
	first, _ := acts[0].(map[string]any)
	if first["email_proven"] != true || first["channel"] != "signin" {
		t.Fatalf("the act is not the one the record screen serves: %v", first)
	}
}

// TestThePackVerifiesItsOwnHashAgainstTheStoredEdition is the self-verification
// property against a REAL published edition: reproduce the version row's
// content_hash from the preimage list and the files in the archive.
//
// The framing is reimplemented here rather than borrowed, so a pack that
// printed a rule it does not follow fails.
func TestThePackVerifiesItsOwnHashAgainstTheStoredEdition(t *testing.T) {
	env := setupTest(t)
	setConsentClock(fixedClock)
	signInAnswering(t, env, "ana@example.com", true, true, false)
	customerID := customerIDFor(t, env, "ana@example.com")
	sessionID := operatorSession(t, env, "operator@example.com")

	pack := downloadPack(t, env, sessionID, evidencePackPath(customerID))
	record := packRecord(t, pack)

	editions, _ := record["editions"].([]any)
	if len(editions) == 0 {
		t.Fatal("record.json names no editions")
	}
	for _, raw := range editions {
		edition, _ := raw.(map[string]any)
		sum := sha256.New()
		for _, rawField := range edition["preimage"].([]any) {
			field, _ := rawField.(map[string]any)
			var value []byte
			if field["field"] == "locale" {
				value = []byte(field["locale"].(string))
			} else {
				path, _ := field["path"].(string)
				body, ok := pack.Files[path]
				if !ok {
					t.Fatalf("the preimage names %q, which is not in the pack", path)
				}
				value = body
			}
			fmt.Fprintf(sum, "%d\n%s", len(value), value)
		}
		reproduced := hex.EncodeToString(sum.Sum(nil))
		if reproduced != edition["content_hash"] {
			t.Fatalf("edition %v: the pack's own files hash to %s, not to the %v it prints",
				edition["label"], reproduced, edition["content_hash"])
		}
		// And the number it prints is the one the DATABASE holds, so the pack
		// verifies against the platform and not merely against itself.
		var stored string
		table := "policy_versions"
		if edition["document"] == "terms" {
			table = "terms_versions"
		}
		if err := env.db.QueryRow(
			`SELECT content_hash FROM `+table+` WHERE id = $1`, edition["id"],
		).Scan(&stored); err != nil {
			t.Fatalf("read the stored hash: %v", err)
		}
		if stored != reproduced {
			t.Fatalf("edition %v: the row holds %s, the pack's files hash to %s",
				edition["label"], stored, reproduced)
		}
	}
}

// TestTwoPacksOverIdenticalActsAreByteIdentical is the ruling migration 118
// rests on. Nothing about the record changes between the two downloads, so the
// only way they can differ is that a clock reached the bytes.
func TestTwoPacksOverIdenticalActsAreByteIdentical(t *testing.T) {
	env := setupTest(t)
	setConsentClock(fixedClock)
	signInAnswering(t, env, "ana@example.com", true, true, false)
	customerID := customerIDFor(t, env, "ana@example.com")
	sessionID := operatorSession(t, env, "operator@example.com")

	first := downloadPack(t, env, sessionID, evidencePackPath(customerID))
	second := downloadPack(t, env, sessionID, evidencePackPath(customerID))

	if !bytes.Equal(first.Body, second.Body) {
		t.Fatalf("two packs over one record differ: %d vs %d bytes", len(first.Body), len(second.Body))
	}
	if first.SHA256 != second.SHA256 || first.SHA256 == "" {
		t.Fatalf("X-Pack-SHA256 = %q then %q", first.SHA256, second.SHA256)
	}
	// The header's hash is the hash of what was sent.
	sum := sha256.Sum256(first.Body)
	if hex.EncodeToString(sum[:]) != first.SHA256 {
		t.Fatal("X-Pack-SHA256 is not the SHA-256 of the body")
	}
	// AND THE FILENAME IS KEYED ON IT (ADR 0067's #546-vs-#548 resolution): not
	// the email, not a digest, and checkable against the file itself.
	if !strings.HasPrefix(first.Filename, "consent-evidence-"+first.SHA256[:16]+"-") {
		t.Fatalf("filename = %q; want it keyed on the pack's own hash", first.Filename)
	}
	if strings.Contains(first.Filename, "ana") || strings.Contains(first.Filename, "example.com") {
		t.Fatalf("the filename names the subject: %q", first.Filename)
	}
}

// TestThePackCarriesPublishedAsAndNoCurrentGatingFlag: the one edition property
// a deterministic document may carry is the one fixed at publication.
func TestThePackCarriesPublishedAsAndNoCurrentGatingFlag(t *testing.T) {
	env := setupTest(t)
	setConsentClock(fixedClock)
	signInAnswering(t, env, "ana@example.com", true, true, false)
	customerID := customerIDFor(t, env, "ana@example.com")
	sessionID := operatorSession(t, env, "operator@example.com")

	record := packRecord(t, downloadPack(t, env, sessionID, evidencePackPath(customerID)))
	for _, raw := range record["editions"].([]any) {
		edition, _ := raw.(map[string]any)
		published, _ := edition["published_as"].(string)
		if published != "gating" && published != "correction" {
			t.Fatalf("published_as = %q", published)
		}
		for _, forbidden := range []string{"standing", "current", "is_current", "satisfying", "gating_now"} {
			if _, present := edition[forbidden]; present {
				t.Fatalf("an edition carries the time-varying field %q", forbidden)
			}
		}
	}
	// Nor anywhere else in the file: a generation date would break determinism
	// just as thoroughly.
	raw := string(packBytes(t, record))
	for _, forbidden := range []string{"generated_at", "generated_on", "downloaded_at"} {
		if strings.Contains(raw, forbidden) {
			t.Fatalf("record.json carries %q; the date belongs in the filename", forbidden)
		}
	}
}

func packBytes(t *testing.T, record map[string]any) []byte {
	t.Helper()
	raw, err := json.Marshal(record)
	if err != nil {
		t.Fatal(err)
	}
	return raw
}

// TestOnePackSpansBothPopulationsAndBothRoutesServeTheSameBytes. A person who
// is both a Customer and staff gets ONE file, and one access request has one
// answer whichever screen the operator reached it from.
func TestOnePackSpansBothPopulationsAndBothRoutesServeTheSameBytes(t *testing.T) {
	env := setupTest(t)
	sessionID := operatorSession(t, env, "zz-operator@example.com")
	orgID := seedOrganization(t, env, "pack-org")

	setConsentClock(fixedClock)
	signInAnswering(t, env, "ana@example.com", true, true, false)
	seedMember(t, env, orgID, "ana@example.com")
	seedStaffAcceptance(t, env, "ana@example.com", currentEditionID(t, env, "terms_versions"))

	customerID := customerIDFor(t, env, "ana@example.com")
	digest := staffDigestFromBrowser(t, env, sessionID, "ana@example.com")

	fromCustomer := downloadPack(t, env, sessionID, evidencePackPath(customerID))
	fromStaff := downloadPack(t, env, sessionID, staffEvidencePackPath(digest))

	if !bytes.Equal(fromCustomer.Body, fromStaff.Body) {
		t.Fatal("the two record screens hand over two different files for one human being")
	}

	record := packRecord(t, fromCustomer)
	if record["customer"] == nil {
		t.Fatal("the pack has no Customer half")
	}
	staff, _ := record["staff"].(map[string]any)
	if staff == nil {
		t.Fatal("the pack has no staff half for somebody who has accepted the Terms as an organizer")
	}
	acceptances, _ := staff["acceptances"].([]any)
	if len(acceptances) != 1 {
		t.Fatalf("staff acceptances = %d; want 1", len(acceptances))
	}
	acceptance, _ := acceptances[0].(map[string]any)
	if acceptance["capacity"] != "organizer" {
		t.Fatalf("capacity = %v; it is carried rather than assumed", acceptance["capacity"])
	}
	// And the staff acceptance's edition resolves to bytes in the same archive.
	edition, _ := acceptance["terms_edition"].(map[string]any)
	found := false
	for _, name := range fromCustomer.Names {
		if strings.HasPrefix(name, "texts/terms/"+edition["label"].(string)+"/") {
			found = true
		}
	}
	if !found {
		t.Fatalf("the staff acceptance names edition %v with no text beside it", edition["label"])
	}
}

// TestAnEmptyPackIsGeneratedRatherThanRefused: "we hold nothing about this
// person" is an answer somebody is entitled to receive as a document.
func TestAnEmptyPackIsGeneratedRatherThanRefused(t *testing.T) {
	env := setupTest(t)
	sessionID := operatorSession(t, env, "zz-operator@example.com")
	orgID := seedOrganization(t, env, "empty-pack-org")

	// On the Staff platform, holding no acceptance and no Customer record: the
	// emptiest subject the platform can produce a pack for.
	seedMember(t, env, orgID, "nothing@example.com")
	digest := staffDigestFromBrowser(t, env, sessionID, "nothing@example.com")

	pack := downloadPack(t, env, sessionID, staffEvidencePackPath(digest))
	if len(pack.Names) != 2 {
		t.Fatalf("an empty pack carries %v; want just the record and its reading", pack.Names)
	}

	record := packRecord(t, pack)
	if record["customer"] != nil {
		t.Fatalf("customer = %v; want null", record["customer"])
	}
	acts, ok := record["customer_acts"].([]any)
	if !ok || len(acts) != 0 {
		t.Fatalf("customer_acts = %v; want an empty array", record["customer_acts"])
	}
	// The pack still states what it does not say, which is exactly the case
	// where a reader is most likely to over-read it.
	raw := string(pack.Files["record.json"])
	if !strings.Contains(raw, "NO ROWS FOR THIS ADDRESS") {
		t.Fatal("the pack does not state that an empty staff section is not a claim about staff")
	}
	if !strings.Contains(raw, "email_proven") {
		t.Fatal("the pack does not state what makes a consent valid")
	}
	if !strings.Contains(raw, "ASSERTED AT THE MOMENT OF CAPTURE") {
		t.Fatal("the pack does not state that the email is the one asserted at capture")
	}
}

// TestTheHMACDigestAppearsNowhereInThePack (#548). Generated by the route
// REACHED BY a digest, which is the case where one would most plausibly leak,
// and checked against the actual digest that was used.
func TestTheHMACDigestAppearsNowhereInThePack(t *testing.T) {
	env := setupTest(t)
	sessionID := operatorSession(t, env, "zz-operator@example.com")
	orgID := seedOrganization(t, env, "digest-pack-org")

	setConsentClock(fixedClock)
	signInAnswering(t, env, "ana@example.com", true, true, false)
	seedMember(t, env, orgID, "ana@example.com")
	seedStaffAcceptance(t, env, "ana@example.com", currentEditionID(t, env, "terms_versions"))
	digest := staffDigestFromBrowser(t, env, sessionID, "ana@example.com")

	pack := downloadPack(t, env, sessionID, staffEvidencePackPath(digest))

	if bytes.Contains(pack.Body, []byte(digest)) {
		t.Fatal("the compressed pack contains the digest it was reached by")
	}
	for name, body := range pack.Files {
		if bytes.Contains(body, []byte(digest)) {
			t.Fatalf("%s carries the Staff Digest", name)
		}
	}
	if strings.Contains(pack.Filename, digest) {
		t.Fatalf("the filename carries the digest: %q", pack.Filename)
	}
	// Nor is the WORD anywhere in the record: a field named for one would be
	// the shape a later change most plausibly reintroduces it in.
	if strings.Contains(string(pack.Files["record.json"]), "digest") {
		t.Fatal("record.json mentions a digest")
	}
}

// TestOnlyTheHashAndTheCoveredActIdsArePersisted: nothing in the database is a
// copy of the pack, and the coverage names every act it disclosed.
func TestOnlyTheHashAndTheCoveredActIdsArePersisted(t *testing.T) {
	env := setupTest(t)
	sessionID := operatorSession(t, env, "zz-operator@example.com")
	orgID := seedOrganization(t, env, "persist-pack-org")

	setConsentClock(fixedClock)
	signInAnswering(t, env, "ana@example.com", true, true, false)
	seedMember(t, env, orgID, "ana@example.com")
	seedStaffAcceptance(t, env, "ana@example.com", currentEditionID(t, env, "terms_versions"))
	customerID := customerIDFor(t, env, "ana@example.com")

	pack := downloadPack(t, env, sessionID, evidencePackPath(customerID))

	var (
		packID string
		stored string
		size   int
	)
	if err := env.db.QueryRow(`
		SELECT id, pack_sha256, size_bytes FROM consent_evidence_packs
		ORDER BY generated_at DESC LIMIT 1
	`).Scan(&packID, &stored, &size); err != nil {
		t.Fatalf("no handover row was written: %v", err)
	}
	if stored != pack.SHA256 || size != len(pack.Body) {
		t.Fatalf("stored %s/%d; the pack was %s/%d", stored, size, pack.SHA256, len(pack.Body))
	}

	// THE COVERAGE IS THE ACTS AND NOTHING ELSE. Both populations, by id.
	rows, err := env.db.Query(`
		SELECT act_kind, act_id FROM consent_evidence_pack_acts WHERE pack_id = $1
	`, packID)
	if err != nil {
		t.Fatalf("read the coverage: %v", err)
	}
	defer rows.Close()
	kinds := map[string]int{}
	for rows.Next() {
		var kind, id string
		if err := rows.Scan(&kind, &id); err != nil {
			t.Fatal(err)
		}
		kinds[kind]++
	}
	if kinds["consent_record"] == 0 || kinds["staff_terms_acceptance"] != 1 {
		t.Fatalf("coverage = %v; want the consent acts and the one staff acceptance", kinds)
	}

	// AND NO COPY OF THE PACK ANYWHERE. The columns on the handover table are
	// the whole of what survives: a hash, a size and a timestamp.
	var columns int
	if err := env.db.QueryRow(`
		SELECT count(*) FROM information_schema.columns
		WHERE table_name = 'consent_evidence_packs'
		  AND data_type IN ('bytea', 'text')
		  AND column_name <> 'pack_sha256'
	`).Scan(&columns); err != nil {
		t.Fatal(err)
	}
	if columns != 0 {
		t.Fatalf("consent_evidence_packs has %d text/bytea columns beside the hash; the pack is never stored", columns)
	}
}

// TestTheEvidencePackIsOperatorOnlyAndHasNoSubjectFacingRoute. The absence is
// the platform's rather than a screen's: a passcode buys a withdrawal, which
// only takes away, where a pack discloses everything.
func TestTheEvidencePackIsOperatorOnlyAndHasNoSubjectFacingRoute(t *testing.T) {
	env := setupTest(t)
	setConsentClock(fixedClock)
	customerSession := signInAnswering(t, env, "ana@example.com", true, true, false)
	customerID := customerIDFor(t, env, "ana@example.com")

	// A signed-in CUSTOMER cannot fetch their own pack.
	if status := routeStatus(t, env, http.MethodGet, evidencePackPath(customerID), customerSession); status == http.StatusOK {
		t.Fatal("a Customer Session downloaded a Consent Evidence Pack")
	}
	// Nor can an anonymous caller.
	if status := routeStatus(t, env, http.MethodGet, evidencePackPath(customerID), ""); status == http.StatusOK {
		t.Fatal("an anonymous caller downloaded a Consent Evidence Pack")
	}
	// And there is no customer-area route that serves one.
	for _, path := range []string{
		"/api/v1/customers/me/evidence-pack",
		"/api/v1/customers/me/consent/evidence-pack",
		"/api/v1/public/consent/evidence-pack",
	} {
		if status := routeStatus(t, env, http.MethodGet, path, customerSession); status != http.StatusNotFound {
			t.Fatalf("GET %s = %d; there is no self-service download", path, status)
		}
	}
}

// TestTheEvidencePackOfSomebodyWhoDoesNotExistIs404 — the record read's own
// refusal, so a stale link is answered the same way whichever thing was
// clicked.
func TestTheEvidencePackOfSomebodyWhoDoesNotExistIs404(t *testing.T) {
	env := setupTest(t)
	sessionID := operatorSession(t, env, "operator@example.com")

	path := evidencePackPath("00000000-0000-0000-0000-000000000000")
	if status := routeStatus(t, env, http.MethodGet, path, sessionID); status != http.StatusNotFound {
		t.Fatalf("GET %s = %d; want 404", path, status)
	}
	staffPath := staffEvidencePackPath(strings.Repeat("a", 32))
	if status := routeStatus(t, env, http.MethodGet, staffPath, sessionID); status != http.StatusNotFound {
		t.Fatalf("GET %s = %d; want 404", staffPath, status)
	}
}

// THE ADULTHOOD DECLARATION IN THE PACK (#590, parent #584, ADR 0069).

// TestOnePackCarriesTheDeclarationForBothPopulations is the payoff, exported:
// one human being, one file, and the declaration in it for the attendee
// capacity and the organizer one — served from the same Go types the record
// screen serves, so the export cannot tell a different story from the screen.
func TestOnePackCarriesTheDeclarationForBothPopulations(t *testing.T) {
	env := setupTest(t)
	sessionID := operatorSession(t, env, "zz-operator@example.com")
	orgID := seedOrganization(t, env, "adulthood-pack-org")

	setConsentClock(fixedClock)
	// The world before the publish, on the staff side: an acceptance under an
	// edition that carried no 18+ Artifact.
	firstEdition := currentEditionID(t, env, "terms_versions")
	seedMember(t, env, orgID, "ana@example.com")
	seedStaffAcceptance(t, env, "ana@example.com", firstEdition)

	// And then the publish, a declaring staff acceptance, and a declaring
	// sign-in as a Customer under the same edition.
	declaringEdition := publishTermsVersionAskingAdulthood(t, env, 2, 0)
	seedStaffAcceptanceDeclaring(t, env, "ana@example.com", declaringEdition)
	signInAnswering(t, env, "ana@example.com", true, true, false)
	customerID := customerIDFor(t, env, "ana@example.com")

	pack := downloadPack(t, env, sessionID, evidencePackPath(customerID))
	record := packRecord(t, pack)

	acts, _ := record["customer_acts"].([]any)
	if len(acts) == 0 {
		t.Fatal("record.json carries no acts")
	}
	signin, _ := acts[0].(map[string]any)
	if signin["adulthood_declaration"] != true {
		t.Fatalf("the sign-in act carries adulthood_declaration=%v; want true", signin["adulthood_declaration"])
	}

	staff, _ := record["staff"].(map[string]any)
	acceptances, _ := staff["acceptances"].([]any)
	if len(acceptances) != 2 {
		t.Fatalf("staff acceptances = %d; want both", len(acceptances))
	}
	declared, _ := acceptances[0].(map[string]any)
	neverAsked, _ := acceptances[1].(map[string]any)
	if declared["adulthood_declaration"] != true {
		t.Fatalf("the declaring acceptance carries %v", declared["adulthood_declaration"])
	}
	// THE NULL SURVIVES INTO THE FILE, present and null rather than dropped:
	// an absent key would leave a regulator to decide what its absence meant.
	value, present := neverAsked["adulthood_declaration"]
	if !present || value != nil {
		t.Fatalf("the older acceptance carries %v (present=%v); want null", value, present)
	}

	// AND THE PDF READS CONSISTENTLY WITH record.json, because it is rendered
	// from record.json's own value. The bytes are compressed, so this asserts
	// only that a reading exists; the words themselves are asserted over the
	// inflated streams in the evidence package's own tests.
	if len(pack.Files["evidence.pdf"]) == 0 {
		t.Fatal("the pack carries no evidence.pdf")
	}
	// NO ROW ANYWHERE SAYS "no". A refusal is refused before any capture.
	if strings.Contains(string(pack.Files["record.json"]), `"adulthood_declaration": false`) {
		t.Fatal("record.json states a refused declaration; a refusal writes nothing")
	}
}

// TestAPackCarryingADeclarationIsStillByteReproducible. "Declared on such a
// date under such an edition" is a finished fact carrying no time-varying
// value, so the ruling migration 118 rests on is untouched by this feature.
func TestAPackCarryingADeclarationIsStillByteReproducible(t *testing.T) {
	env := setupTest(t)
	sessionID := operatorSession(t, env, "operator@example.com")

	setConsentClock(fixedClock)
	publishTermsVersionAskingAdulthood(t, env, 2, 0)
	signInAnswering(t, env, "ana@example.com", true, true, false)
	customerID := customerIDFor(t, env, "ana@example.com")

	first := downloadPack(t, env, sessionID, evidencePackPath(customerID))
	second := downloadPack(t, env, sessionID, evidencePackPath(customerID))
	if !bytes.Equal(first.Body, second.Body) {
		t.Fatalf("two packs over one declaring record differ: %d vs %d bytes",
			len(first.Body), len(second.Body))
	}
	if first.SHA256 != second.SHA256 {
		t.Fatalf("X-Pack-SHA256 = %q then %q", first.SHA256, second.SHA256)
	}
	// The declaration really is in the bytes being compared — otherwise this
	// would be asserting determinism over a file that never carried it.
	if !strings.Contains(string(first.Files["record.json"]), `"adulthood_declaration": true`) {
		t.Fatal("the pack carries no declaration, so its determinism proves nothing about one")
	}
}

// TestWithdrawalsInThePackAreTheActsThemselves: no synthesised log, and the act
// reads as a withdrawal because it carries what the consent WAS.
func TestWithdrawalsInThePackAreTheActsThemselves(t *testing.T) {
	env := setupTest(t)
	setConsentClock(fixedClock)
	signInAnswering(t, env, "ana@example.com", true, true, false)
	customerID := customerIDFor(t, env, "ana@example.com")
	sessionID := operatorSession(t, env, "operator@example.com")

	// The clock is advanced so the withdrawal is a distinct row on the keyset
	// walk: the harness's clock is fixed and two acts on one tick are a coin
	// toss.
	setConsentClock(fixedClock.Add(time.Hour))
	withdrawalPath := operatorConsentWithdrawalPath(customerID)
	resp, body := env.post(t, withdrawalPath, map[string]any{
		"marketing_consent": false,
		"request_reference": "subject request 4711",
	}, authHeader(sessionID))
	if resp.StatusCode != http.StatusOK {
		t.Fatalf("withdrawal status=%d body=%+v", resp.StatusCode, body.Error)
	}

	record := packRecord(t, downloadPack(t, env, sessionID, evidencePackPath(customerID)))
	for _, forbidden := range []string{"withdrawals", "withdrawal_log"} {
		if _, present := record[forbidden]; present {
			t.Fatalf("record.json carries a synthesised %q section", forbidden)
		}
	}
	acts, _ := record["customer_acts"].([]any)
	newest, _ := acts[0].(map[string]any)
	if newest["marketing_consent"] != false || newest["prior_marketing_consent"] != "granted" {
		t.Fatalf("the withdrawal does not read as one: %v", newest)
	}
	// NULL KEEPS MEANING "NOT SHOWN": the operator surface showed no document,
	// so `presented_locale` is absent entirely rather than null.
	if _, present := newest["presented_locale"]; present {
		t.Fatal("presented_locale is present on a channel that shows no document")
	}
}
