-- Customer Sessions: the server-side sign-in record a Customer earns by proving
-- ownership of their email with a one-time passcode (ADR 0010, PRD #55).
--
-- This is deliberately its own table rather than a column on `sessions`. A
-- Customer Session and a Staff Session are unrelated records: they authorize
-- different domains, live on different origins, and nothing links a Customer to
-- a Member even where the email matches. Reusing `sessions` would have overloaded
-- `active_member_id IS NULL` — today "authenticated staff with no Organization
-- selected" — to also mean "this is a shopper", inside the code that gates
-- tenancy.

CREATE TABLE customer_sessions (
    -- An opaque high-entropy token, generated by the service and never derived
    -- from anything about the Customer. It is the primary key so a lookup is the
    -- credential check, exactly as `sessions.id` is for staff.
    id TEXT PRIMARY KEY,
    customer_id UUID NOT NULL REFERENCES customers (id) ON DELETE CASCADE,
    -- The scope of the session. NULL means a full Customer Session: every Ticket
    -- Sale the Customer owns, across every Organization. A Ticket Sale reference
    -- narrows the session to exactly that one sale — the Confirmation Link
    -- session, which is not issued yet. The column ships nullable and unused by
    -- writers so adding Confirmation Links later is a new code path rather than a
    -- reshaping of this record.
    ticket_sale_id UUID REFERENCES ticket_sales (id) ON DELETE CASCADE,
    -- Sliding: extended on every authenticated use. Customers buy months ahead
    -- and return at the door, so the window is far longer than a Staff Session's.
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Supports revoking or enumerating one Customer's sessions.
CREATE INDEX customer_sessions_customer_id_idx ON customer_sessions (customer_id);
-- Supports sweeping expired sessions.
CREATE INDEX customer_sessions_expires_at_idx ON customer_sessions (expires_at);
