definitions:
  main.healthResponse:
    properties:
      status:
        example: ok
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      description: Returns service health status.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.healthResponse'
      summary: Health check
      tags:
      - public
swagger: "2.0"
