package service

import (
	"context"
	"strings"
)

// GetCheckoutReversal answers, for one online checkout, whether the Ticket Sale
// it produced can be undone right now and by when (#121, ADR 0018).
//
// This is the guest half of a rule the Customer Area already publishes. Online
// checkout is guest-facing — nobody has to sign in to buy — so the buyer most
// likely to want an undo is the one least equipped to reach it: reversal itself
// requires a Customer Session, and a page that says nothing about the window
// leaves them emailing the Organization, which is the outcome self-service was
// meant to remove.
//
// It is a read and only a read. Nothing here reverses anything, and it is
// deliberately impossible to: this function returns two facts and calls nothing
// that mutates. The action stays behind a Customer Session, as ADR 0018 requires,
// and this endpoint's entire job is to tell somebody the deadline and let the
// Storefront offer them the door.
//
// clientTransactionID is our own id for the checkout, not an identifier of a
// person: it names one attempt, was generated by begin-checkout, and cannot be
// widened into a purchase history or an email. Nothing personal comes back
// either — a deadline and a boolean, so an id guessed or forwarded reveals no
// more than a clock does.
//
// Everything unanswerable answers the same way, with the zero offer: a blank id,
// an id nobody ever issued, a Payment still pending or failed, a checkout whose
// sale was never recorded. A guest is told "no undo on offer" in every one of
// those cases, and the page simply says nothing about undoing rather than
// explaining which kind of nothing it found.
func (s *Service) GetCheckoutReversal(ctx context.Context, clientTransactionID string) (*ReversalOffer, error) {
	id := strings.TrimSpace(clientTransactionID)
	if id == "" {
		return &ReversalOffer{}, nil
	}

	facts, err := s.repo.ReversalFactsForCheckout(ctx, id)
	if err != nil {
		return nil, err
	}
	if facts == nil {
		return &ReversalOffer{}, nil
	}

	// The same call the Customer Area's cards make, on the same facts, against
	// the same clock and the same Payment Provider capability. That shared call
	// is the guarantee that the deadline a guest reads here is the deadline they
	// will read on their own sale once they sign in.
	offer := reversalOffer(*facts, s.now(), s.reversal)
	return &offer, nil
}
